"""Update relationship

Revision ID: a808ffadab3f
Revises: 402649c4e040
Create Date: 2016-07-27 03:23:14.985473

"""

# revision identifiers, used by Alembic.
revision = 'a808ffadab3f'
down_revision = '402649c4e040'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifications',
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], )
    )
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column(u'books', 'category_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'books', sa.Column('category_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'books', 'categories', ['category_id'], ['id'])
    op.drop_table('classifications')
    ### end Alembic commands ###
